replicaCount: 1
appName: task-management
replicas: 1

container:
  containerName: task-management
  containerPort: 9001
  image: task_management
  imagePullPolicy: Never
  env:
    - name: PYTHONPATH
      value: /app
    - name: REDIS_HOST
      value: redis
    - name: REDIS_PORT
      value: "6379"

service:
  type: ClusterIP
  port: 9001
  targetPort: 9001
  name: task-management
