### Register
POST http://localhost:8000/user/auth/register

{
  "username":"ansh",
  "email":"a@a.com",
  "password":"a10312"
}


### Login Request
POST http://localhost:8000/user/auth/login
Content-Type: application/x-www-form-urlencoded

username=a@a.com&password=a10312

###
@accesstoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYzY4Y2Q5Zi1hYmI5LTQxMWYtODZkNC1kMjM3ZmUxOGQzZjYiLCJleHAiOjE3NDM5OTU5Mzd9.LUDAiFBlQ9tyAl0wXhUlsi2D4rnouXKAlC_42Ke3kVg

###
GET http://localhost:8000/user/user
Authorization: Bearer {{accesstoken}}

###
GET http://localhost:8000/task/tasks
Authorization: Bearer {{accesstoken}}

###
POST http://localhost:8000/task/tasks
Authorization: Bearer {{accesstoken}}

{
  "title": "complete this",
  "description": "must be completed",
  "state": "planned",
  "priority": "medium",
  "assigned_to": "11d5ea29-ddf0-403d-b1db-8fb587395808"
}
###

###
PATCH http://localhost:8000/task/tasks/8fa48533-bd71-42d3-aff9-91fa866bf26d
Authorization: Bearer {{accesstoken}}

{
  "priority": "low"
}
###

###
GET http://localhost:8000/task/tasks/history/76c611e0-4bf7-4f60-9934-858e7a0e8f1c
Authorization: Bearer {{accesstoken}}
###
