events {
    worker_connections 1024;
}

http {
    upstream user_management {
        server user_management:9009;
    }

    upstream task_management {
        server task_management:9001;
    }

    server {
        listen 80;

        # JWT Validation (via auth_request)
        location = /_validate_token {
            internal;
            proxy_pass http://user_management/auth/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
        }
        location /user/auth/ {
            proxy_pass http://user_management/auth/;
        }
        # User Management Service
        location /user/ {
            auth_request /_validate_token;
            auth_request_set $user_id $upstream_http_x_user_id;
            proxy_set_header X-User-ID $user_id;
            proxy_pass http://user_management/;
        }

        # Task Management Service
        location /task/ {
            auth_request /_validate_token;
            auth_request_set $user_id $upstream_http_x_user_id;
            proxy_set_header X-User-ID $user_id;
            proxy_pass http://task_management/;
        }
        location /notification {
            proxy_pass http://notification/;
        }
        # Health checks (no auth)
        location /health {
            return 200 "OK";
        }
    }
}