apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "notifications" }}
spec:
  selector:
    app: {{ .Values.service.name | default "notifications" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 9002 }}
      targetPort: {{ .Values.service.targetPort | default 9002 }}
  type: {{ .Values.service.type }}